server:
  port: 8080
  context-path: /

spring:
    jpa:
#      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
#          enable_lazy_load_no_trans: true
    h2:
      console:
        enabled: true
logging:
  level:
    org.hibernate.SQL: debug
